with open('ui/theme.py', 'w', encoding='utf-8') as f:
    f.write('"""Indian Railways Section Control desk theme + Plotly map drawing helpers."""\n')
    f.write('from __future__ import annotations\n\n')
    f.write('import plotly.graph_objects as go\n\n')
    f.write('from engine.model import PRIORITY_COLOR, PRIORITY_LABEL\n\n')
    f.write('# IR Control Sheet palette — light operations-room look\n')
    f.write('PAGE_BG = "#eef1f4"        # warm paper / control sheet\n')
    f.write('HEADER_BG = "#1b2a4a"      # ink navy header bar\n')
    f.write('HEADER_RED = "#c8102e"     # IR red strip\n')
    f.write('CARD_BG = "#ffffff"        # white cards\n')
    f.write('CARD_BORDER = "#d0d5dd"    # card border\n')
    f.write('TEXT = "#1b2430"           # primary text\n')
    f.write('MUTED = "#5c6773"          # muted text\n')
    f.write('SIGNAL_GREEN = "#1f8a4c"   # signal green\n')
    f.write('SIGNAL_AMBER = "#c48a00"   # signal amber\n')
    f.write('SIGNAL_RED = "#c8102e"     # danger red / IR red\n')
    f.write('PLOT_BG = "#f7f8fa"        # light map background\n')
    f.write('RAIL_GREY = "#6b7b8d"      # rail colour (grey-blue)\n')
    f.write('RAIL_GREY_DARK = "#4a5a6a" # darker rail for double line\n\n')
    f.write('# Backward-compat aliases used by app.py\n')
    f.write('BG = PAGE_BG\n')
    f.write('GREEN = SIGNAL_GREEN\n')
    f.write('RED = SIGNAL_RED\n')
    f.write('ACCENT = HEADER_RED\n')
    f.write('PANEL = "#f3f5f8"\n')
    f.write('CARD = CARD_BG\n\n')

print('Part 1 done')