with open('ui/theme.py', 'a', encoding='utf-8') as f:
    f.write('def draw_map(sim) -> go.Figure:\n')
    f.write('    net = sim.net\n')
    f.write('    fig = go.Figure()\n\n')
    f.write('    finished_trains = [t for t in sim.trains if t.finished]\n')
    f.write('    finished_at_station = {}\n')
    f.write('    for t in finished_trains:\n')
    f.write('        if t.at_station:\n')
    f.write('            finished_at_station.setdefault(t.at_station, []).append(t)\n\n')
    f.write('    for blk in net.blocks:\n')
    f.write('        x1, y1, x2, y2 = net.block_xy(blk)\n')
    f.write('        occupied = bool(blk.occupant_up or blk.occupant_down)\n\n')
    f.write('        if blk.double_line:\n')
    f.write('            fig.add_trace(go.Scatter(\n')
    f.write('                x=[x1, x2], y=[y1 + 0.35, y2 + 0.35],\n')
    f.write('                mode="lines", line=dict(width=5, color=RAIL_GREY_DARK),\n')
    f.write('                hoverinfo="none", showlegend=False,\n')
    f.write('            ))\n')
    f.write('            fig.add_trace(go.Scatter(\n')
    f.write('                x=[x1, x2], y=[y1 - 0.35, y2 - 0.35],\n')
    f.write('                mode="lines", line=dict(width=5, color=RAIL_GREY_DARK),\n')
    f.write('                hoverinfo="none", showlegend=False,\n')
    f.write('            ))\n')
    f.write('            fig.add_trace(go.Scatter(\n')
    f.write('                x=[x1, x2], y=[y1, y2],\n')
    f.write('                mode="lines", line=dict(width=1, color=RAIL_GREY, dash="dot"),\n')
    f.write('                hoverinfo="none", showlegend=False,\n')
    f.write('            ))\n')
    f.write('        else:\n')
    f.write('            dash = "dash" if not occupied else "solid"\n')
    f.write('            width = 3 if not occupied else 4\n')
    f.write('            color = RAIL_GREY if not occupied else SIGNAL_AMBER\n')
    f.write('            fig.add_trace(go.Scatter(\n')
    f.write('                x=[x1, x2], y=[y1, y2],\n')
    f.write('                mode="lines", line=dict(width=width, color=color, dash=dash),\n')
    f.write('                hoverinfo="text",\n')
    f.write('                hovertext=f"{blk.id} \xb7 Single-line \xb7 {blk.length_km} km \xb7 {\'Occupied\' if occupied else \'Clear\'}",\n')
    f.write('                showlegend=False,\n')
    f.write('            ))\n\n')
    f.write('        if not blk.double_line and blk.id in getattr(sim, "predicted_conflicts", set()):\n')
    f.write('            fig.add_trace(go.Scatter(\n')
    f.write('                x=[x1, x2], y=[y1, y2],\n')
    f.write('                mode="lines", line=dict(width=8, color=SIGNAL_RED, dash="solid"),\n')
    f.write('                opacity=0.18, hoverinfo="none", showlegend=False,\n')
    f.write('            ))\n\n')

print('Part 3 done')