with open('ui/theme.py', 'a', encoding='utf-8') as f:
    f.write('    station_offsets = {}\n')
    f.write('    block_offsets = {}\n')
    f.write('    active_at_station = {}\n\n')
    f.write('    for stn in net.stations:\n')
    f.write('        x, y = net.station_xy(stn)\n')
    f.write('        loop_count = len(stn.loops)\n')
    f.write('        \n')
    f.write('        box_w = 1.6 + loop_count * 0.35\n')
    f.write('        box_h = 0.9\n')
    f.write('        \n')
    f.write('        fig.add_trace(go.Scatter(\n')
    f.write('            x=[x - box_w/2, x + box_w/2, x + box_w/2, x - box_w/2, x - box_w/2],\n')
    f.write('            y=[y - box_h/2, y - box_h/2, y + box_h/2, y + box_h/2, y - box_h/2],\n')
    f.write('            mode="lines", fill="toself",\n')
    f.write('            fillcolor=CARD_BG,\n')
    f.write('            line=dict(width=1.5, color=RAIL_GREY),\n')
    f.write('            hoverinfo="text",\n')
    f.write('            hovertext=f"{stn.id} \xb7 {stn.name} \xb7 {loop_count} loops",\n')
    f.write('            showlegend=False,\n')
    f.write('        ))\n')
    f.write('        \n')
    f.write('        fig.add_trace(go.Scatter(\n')
    f.write('            x=[x], y=[y + box_h/2 + 0.35],\n')
    f.write('            mode="text",\n')
    f.write('            text=[stn.id],\n')
    f.write('            textfont=dict(size=10, color=HEADER_BG, family="monospace", weight=700),\n')
    f.write('            hoverinfo="none", showlegend=False,\n')
    f.write('        ))\n')
    f.write('        \n')
    f.write('        if loop_count > 1:\n')
    f.write('            fig.add_trace(go.Scatter(\n')
    f.write('                x=[x + box_w/2 - 0.2], y=[y - box_h/2 - 0.25],\n')
    f.write('                mode="text",\n')
    f.write('                text=[f"L{loop_count}"],\n')
    f.write('                textfont=dict(size=8, color=MUTED, weight=600),\n')
    f.write('                hoverinfo="none", showlegend=False,\n')
    f.write('            ))\n\n')
    f.write('        if stn.id in finished_at_station:\n')
    f.write('            for i, t in enumerate(finished_at_station[stn.id]):\n')
    f.write('                fig.add_trace(go.Scatter(\n')
    f.write('                    x=[x + (i - len(finished_at_station[stn.id])/2 + 0.5) * 0.4],\n')
    f.write('                    y=[y + box_h/2 + 0.6],\n')
    f.write('                    mode="markers",\n')
    f.write('                    marker=dict(size=6, color=PRIORITY_COLOR[t.priority], opacity=0.3, symbol="circle"),\n')
    f.write('                    hoverinfo="text",\n')
    f.write('                    hovertext=f"FINISHED \xb7 {t.number} {t.name}",\n')
    f.write('                    showlegend=False,\n')
    f.write('                ))\n\n')
    f.write('        for t in sim.trains:\n')
    f.write('            if t.at_station == stn.id and t.entered_section and not t.finished:\n')
    f.write('                active_at_station.setdefault(stn.id, []).append(t)\n\n')
    f.write('        trains_here = active_at_station.get(stn.id, [])\n')
    f.write('        for i, t in enumerate(trains_here):\n')
    f.write('            station_offsets[(stn.id, t.id)] = (i - (len(trains_here) - 1) / 2) * 0.5\n\n')

print('Part 4 done')